# Generated by Django 5.0.1 on 2024-02-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usedbook1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
