# Generated by Django 5.0.1 on 2024-02-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usedbook1', '0002_alter_book_stock_quantity'),
        ('usedbook1', '0003_alter_cartitem_user'),
    ]

    operations = [
    ]
