# Generated by Django 5.0.1 on 2024-02-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usedbook1', '0004_merge_20240207_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
